### ISSUE TITLE
rinari-web-server fails after fixing issue 42# in Windows platform.

### ISSUE THREAD

**Issue by JamesYuan** [eschulte/rinari#52]
I think this issue is caused by the #42.

In function 'rinari-web-server', it runs (ruby-compilation-run command nil "server")), the command is "ruby c:/dev/scripts/Ruby/first_app/script/rails server" .

In function 'ruby-compilation-run', it runs (ruby-compilation-do name cmdlist), the name is "server", but the cmdlist will be expanded with 
 
("ruby" "c:/dev/scripts/Ruby/first_app/ruby" "c:/dev/scripts/Ruby/first_app/script/rails" "server").

No such "c:/dev/scripts/Ruby/first_app/ruby", it fails.

Also I appended a comment in the issue #42 about the 'rails' in %PATH%, if you have time, please help check it. 

Thank you.

**Comment by purcell** [comment]
This is now fixed. Sorry it took so long.
