### ISSUE TITLE
format buffer is very slowly in rhtml-mode.

### ISSUE THREAD

**Issue by zw963** [eschulte/rinari#91]
When I run following command in one slightly biger erb file opened with rhtml-mode.
will cause a notable times deay to wait format this buffer correct.

```cl
(indent-region (point-min) (point-max))
```

**Comment by zw963** [comment]
BTW: The same file, if use [web-mode](http://web-mode.org/), file got indented very quickly.

**Comment by purcell** [comment]
`rhtml-mode` is not part of `rinari`, sorry. Did you mean to report this here instead: https://github.com/eschulte/rhtml ?

**Comment by zw963** [comment]
That guy seem like disappeared from earth ...

that why i create issues here ...

fine, just forget it.

**Comment by dcorking** [comment]
@zw963 Billy, try mmm-mode, for example the ERB configuration in [purcell/emacs.d](/purcell/emacs.d)

**Comment by purcell** [comment]
Yup, works pretty well for me. Not perfect, but particularly if you've got a very recent Emacs version, it's a good option.

**Comment by zw963** [comment]
Cool, in fact I had star your's dotfiles for a long time.

I have personal defined config too with all needed package saved 
in local directory, so many dotfiles help me a lot for this.

I never use `mmm-mode`, but i have used `multi-web-mode` for a while,
i have a question about this: 
Does mmm-mode is work well with `undo-tree` ?
`multi-web-mode` is fine, But, when i switch from one mode(html-mode) to
another mode(js-mode), all undo history is clean up, that is the thing i can 
not accept. 

thanks

**Comment by purcell** [comment]
> Does mmm-mode is work well with undo-tree ?

Yes, should be fine.
